#[project]
#src = "src"
#out = "out"
#dot_env = ".env" # better put on another location
#dependencies = ["snekmate"]

[networks.pyevm]
is_zksync = false


[networks.anvil]
url = "http://127.0.0.1:8545"
prompt_live = false
save_to_db = false
default_account_name = "anvil1"
chain_id = 31337

[networks.anvil-zksync]
url = "http://127.0.0.1:8011"
prompt_live = false
is_zksync = true
default_account_name = "anvil-zksync"
chain_id = 260


[networks.sepolia]
url = "https://ethereum-sepolia-rpc.publicnode.com"
chain_id = 11155111

[networks.zksync-sepolia]
url = "https://sepolia.era.zksync.dev"
chain_id = 300
is_zksync = true
prompt_live = true


[networks.our_fake_chain_free] # pw like anvil
url = "$TENDERLY_RPC_URL"
save_to_db = false
prompt_live = false
default_account_name = "tenderly1"

# You can view all configuration options at https://cyfrin.github.io/moccasin/all_moccasin_toml_parameters.html
